version: '3.9'

services:

  qrcodedb:
    image: postgres:12.17-alpine3.19
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgres

  setup:
    depends_on:
      - qrcodedb
    build:
      context: .
    env_file: ./.env
    ports:
      - "6060:9191"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://qrcodedb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
        "spring.datasource.username" : "$POSTGRESDB_USER",
        "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
      - ./src/main/resources:/app/src/main/resources
    stdin_open: true
    tty: true

volumes:
  db: